function T = readtf(path)
%READTF Reads the transformation from the file as generated by
%        xtion_calibration_capture.
%
% SYNOPSIS
%   T = readtf(path)
%
% INPUT
%   path    Path the tf file.
%
% OUTPUT
%   T       Transformation matrix
%

% Libor Wagner on April 30, 2013

    % Check whether file exists
    if (exist(path, 'file') == 2)
        T = csvread(path);
    else
        error('File %s does not exist!', path);
    end

end
