function [name, pos] = readjoints(path)
%READJOINTS Reads the joint positions from the file as generated by
%        xtion_calibration_capture.
%
% SYNOPSIS
%   [name, pos] = readjoints(path)
%
% INPUT
%   path    Path the joints file.
%
% OUTPUT
%   name    Cell array of the joint names.
%   pos     Positions of the joints pos(i) is position of the name(i) joint.
%

% Libor Wagner on April 30, 2013

    % Check whether file exists
    if (exist(path, 'file') == 2)
        f = fopen(path);
        % Read header
        textscan(f, '%s %s %s %s\n', 1, 'delimiter', ',', 'CollectOutput', 1);
        C = textscan(f, '%s %f %f %f\n', 'delimiter', ',', 'CollectOutput', 1);
        fclose(f);
        name = C{1};
        pos = C{2}; pos = pos(:,1);
    else
        error('File %s does not exist!', path);
    end

end
