joint_limits:
  ext_axis:
    has_velocity_limits: true
    max_velocity: 0.568978
    has_acceleration_limits: false
    max_acceleration: 0
  r2_joint_t:
    has_velocity_limits: true
    max_velocity: 2.1293
    has_acceleration_limits: false
    max_acceleration: 0
  r2_joint_grip:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  r1_joint_s:
    has_velocity_limits: true
    max_velocity: 0.767944
    has_acceleration_limits: false
    max_acceleration: 0
  r1_joint_l:
    has_velocity_limits: true
    max_velocity: 3.49066
    has_acceleration_limits: false
    max_acceleration: 0
  r1_joint_u:
    has_velocity_limits: true
    max_velocity: 0.698132
    has_acceleration_limits: false
    max_acceleration: 0
  r1_joint_r:
    has_velocity_limits: true
    max_velocity: 1.43117
    has_acceleration_limits: false
    max_acceleration: 0
  r1_joint_b:
    has_velocity_limits: true
    max_velocity: 1.43117
    has_acceleration_limits: false
    max_acceleration: 0
  r1_joint_t:
    has_velocity_limits: true
    max_velocity: 2.1293
    has_acceleration_limits: false
    max_acceleration: 0
  r1_joint_grip:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0
  r2_joint_s:
    has_velocity_limits: true
    max_velocity: 0.767944
    has_acceleration_limits: false
    max_acceleration: 0
  r2_joint_l:
    has_velocity_limits: true
    max_velocity: 0.698132
    has_acceleration_limits: false
    max_acceleration: 0
  r2_joint_u:
    has_velocity_limits: true
    max_velocity: 0.767944
    has_acceleration_limits: false
    max_acceleration: 0
  r2_joint_r:
    has_velocity_limits: true
    max_velocity: 1.43117
    has_acceleration_limits: false
    max_acceleration: 0
  r2_joint_b:
    has_velocity_limits: true
    max_velocity: 1.43117
    has_acceleration_limits: false
    max_acceleration: 0