<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"> 
	<xacro:macro name="dx100" params="*origin parent color height"> 
		<link name="dx100">
			<xacro:default_inertial/>
			<visual>
				<geometry>
					<box size="0.8 0.8 ${height}" />
				</geometry>
				<material name="${color}" />
				<origin xyz="0 0 ${height/2}"/>
			</visual>
			<collision>
				<geometry>
					<box size="0.8 0.8 ${height}" />
				</geometry>
				<origin xyz="0 0 ${height/2}"/>
			</collision>
		</link>
		<joint name="joint_f_dx100" type="fixed">
			<insert_block name="origin" />
			<parent link="${parent}"/>
			<child link="dx100"/>
		</joint>
	</xacro:macro>
</robot>
