<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"> 

	<xacro:macro name="table_leg" params="*origin parent suffix color height"> 
		<link name="${suffix}">
			<xacro:default_inertial/>
			<visual>
				<geometry>
					<box size="0.05 0.05 ${height-0.150}" />
				</geometry>
				<material name="${color}" />
				<origin xyz="0.025 0.025 -${(height+0.15)/2}"/>
			</visual>
		</link>
		<joint name="${suffix}joint_ftable_leg" type="fixed">
			<xacro:insert_block name="origin" />
			<parent link="${parent}"/>
			<child link="${suffix}"/>
		</joint>
	</xacro:macro>
	<xacro:macro name="table" params="*origin parent suffix color height deskx desky"> 
		<link name="${suffix}desk">
			<xacro:default_inertial/>
			<visual>
				<geometry>
					<box size="${deskx} ${desky} 0.15" />
				</geometry>
				<material name="${color}" />
				<origin xyz="0 0 ${-0.075}"/>
			</visual>
		</link>
		<joint name="${suffix}joint_ftable" type="fixed">
			<xacro:insert_block name="origin" />
			<parent link="${parent}"/>
			<child link="${suffix}desk"/>
		</joint>
		<xacro:table_leg parent="${suffix}desk" suffix="${suffix}leg_1" color="${color}" height="${height}">
			<origin xyz="${deskx/2} ${desky/2} 0.0" rpy="0 0 ${PI}"/>
		</xacro:table_leg>
		<xacro:table_leg parent="${suffix}desk" suffix="${suffix}leg_2" color="${color}" height="${height}">
			<origin xyz="${deskx/2} -${desky/2} 0.0" rpy="0 0 ${PI/2}"/>
		</xacro:table_leg>
		<xacro:table_leg parent="${suffix}desk" suffix="${suffix}leg_3" color="${color}" height="${height}">
			<origin xyz="-${deskx/2} -${desky/2} 0.0" rpy="0 0 0"/>
		</xacro:table_leg>
		<xacro:table_leg parent="${suffix}desk" suffix="${suffix}leg_4" color="${color}" height="${height}">
			<origin xyz="-${deskx/2} ${desky/2} 0.0" rpy="0 0 ${-PI/2}"/>
		</xacro:table_leg>
	</xacro:macro>
</robot>
