.PHONY: all clean
all:
	@$(MAKE) --no-print-directory -C shImage
	@$(MAKE) --no-print-directory -C Ngin
	@$(MAKE) --no-print-directory -C Ngin3d
	@$(MAKE) --no-print-directory -C shFont
clean:
	@$(MAKE) --no-print-directory -C shImage clean
	@$(MAKE) --no-print-directory -C Ngin clean
	@$(MAKE) --no-print-directory -C Ngin3d clean
	@$(MAKE) --no-print-directory -C shFont clean
